(LIB) allocators are features 'jemalloc' 'mimalloc'

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -101,10 +101,27 @@ jobs:
         shell: bash
         run: |
           set -eux
+          export CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
           cargo --version
           rustc --print cfg
-          cargo build --locked --verbose
+          cargo build --locked
           cargo build --locked --release
+          ./target/release/s4 --help
+      - name: Build using rust ${{ matrix.msrv }} on ${{ matrix.os }} --features mimalloc
+        shell: bash
+        run: |
+          set -eux
+          export CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
+          cargo build --locked --release --features mimalloc
+          ./target/release/s4 --help
+      - name: Build using rust ${{ matrix.msrv }} on ${{ matrix.os }} --features jemalloc
+        shell: bash
+        # jemalloc builds fails on github Windows
+        if: ${{ matrix.os != 'windows-latest' }}
+        run: |
+          set -eux
+          export CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
+          cargo build --locked --release --features jemalloc
           ./target/release/s4 --help
       - name: Upload release binary ${{ matrix.msrv }} for ${{ matrix.os }}
         if: ${{ matrix.os == 'windows-latest' && matrix.msrv == env.MSRV_UPLOAD }}
@@ -165,6 +182,8 @@ jobs:
           cargo --version
           cargo build --locked --release --verbose
           cp -av ./target/release/s4 ./s4_release
+          cargo build --locked --release --features mimalloc
+          cargo build --locked --release --features jemalloc
       - name: Upload release binary for test
         uses: actions/upload-artifact@v4
         with:
